#!/usr/bin/env bash
set -o nounset

DEFAULT_IMAGE_SOURCE="${HOME}/Downloads/images"
DEFAULT_OUTPUT_DIR="$(pwd)/output"

WEIGHTS_DIR="$(pwd)/models/MobileNet"
WEIGHTS_FILE_AESTHETIC="${WEIGHTS_DIR}/weights_mobilenet_aesthetic_0.07.hdf5"
WEIGHTS_FILE_TECHNICAL="${WEIGHTS_DIR}/weights_mobilenet_technical_0.11.hdf5"


# Usage: predict WEIGHTS_OPTION [IMAGE_SOURCE] [OUTPUT_DIR]
#   WEIGHTS_OPTION: Either 'aesthetic' or 'technical'
#   IMAGE_SOURCE:   Optional image source file/dir (otherwise use default)
#   OUTPUT_DIR:     Optional output dir (otherwise use default)
function predict() {
    WEIGHTS_OPTION=$1
    OUTPUT_FILE="iqa_${WEIGHTS_OPTION}.json"
    IMAGE_SOURCE="$(realpath ${2:-$DEFAULT_IMAGE_SOURCE})"
    OUTPUT_DIR="${3:-$DEFAULT_OUTPUT_DIR}"

    # Pick an output filename based on the weights file
    mkdir -p $OUTPUT_DIR
    if [[ "$WEIGHTS_OPTION" == *"aesthetic"* ]]; then
        WEIGHTS_FILE=$WEIGHTS_FILE_AESTHETIC
    else
        WEIGHTS_FILE=$WEIGHTS_FILE_TECHNICAL
    fi

    docker run \
        -v "$IMAGE_SOURCE":/src/images \
        -v "$WEIGHTS_FILE":/src/weights.hdf5 \
        -v "$OUTPUT_DIR":/src/output \
        nima-cpu /src/output/$OUTPUT_FILE
}


# find $DEFAULT_IMAGE_SOURCE -type f -size -100c -delete -printf "%h/%f\n"
# find $DEFAULT_IMAGE_SOURCE -type f -size -100c -printf "%h/%f\n" > invalid_images.txt
predict "$@"
